### ISSUE TITLE
Not sending out digest email.

### ISSUE THREAD

**Issue by maverjk** [enricotagliavini/fail2ban-digest#1]
@enricotagliavini 
Hi Enrico

Really nice project! As already told you in the [other post](https://github.com/fail2ban/fail2ban/issues/832#issuecomment-395764250) I kept testing your script but I'm having an issue. Maybe you can give me an help to track down what is the problem. 
Basically I have setup the cron job but I do not got any digest email. I had a notification email informing me about jails stopped after a reload, but in general not the digest one. The command "fail2ban_digest digest sshd" works properly giving me a complete list of all IP and I can also see that it got empty after this command "fail2ban_digest maildigest sshd" but no email is received. 

To answer to your comment about shebang, in my case and in my environment, I had to hardcode it "#!/usr/bin/python3.6" to make it works. With "#!/usr/bin/env python3" I got this error "/usr/bin/env: python3: No such file or directory"

Then of course we can discuss of some improvements that in my opinion would be really great. 
For example about timer that we have already discussed as well as the possibility to have one digest email for all jails enabled. At the moment I have setup my jail.local as in your example:

> [DEFAULT]
> action = %(action_mwl)s
> action_digest = %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
>                 digest[name=%(__name__)s, chain="%(chain)s"]
> 
> [sshd]
> enabled = true
> action = %(action_digest)s

I presume that if I'm going to setup it under all my 8 jails, the script is going to create 8 different db as well as I'll need to create 8 cron jobs to specify my different db-jails 
ex: fail2ban_digest maildigest sshd 
     fail2ban_digest maildigest postfix ect..

However let me know if I'm wrong and if I can help in some way.
Thanks

**Comment by enricotagliavini** [comment]
Do you have a system MTA running? The digest program tried to connect to the local SMTP server to send the email. I use postfix, but there are many alternatives available.

What system are you running on? As I said the recommended way is to always have a ```/usr/bin/python3```, pointing to some more specific version, like python 3.6. But I cannot use python3.6 in my shebang and that would break when running on python3.4 which is fully supported as well. Every software vendor is free to configure python the way they like obviously, but trying to catch them all is simply impossible. I simply follow what mainstream distributions such as Red Hat, Fedora, Ubuntu and the like are doing, so it works out of the box there. Ok in Red Hat / CentOS you need to install python34 from EPEL repo, but that's a common one, almost I must I would say.

It is also possible to use it via scl in CentOS and Red Hat. But in that case you have to run the command with ```/usr/bin/scl enable rh-python36 fail2ban_digest```, that would still work with the shebang I used.

**Comment by maverjk** [comment]
Hi Enrico 

I'm using CentOS 7. This is part of my jail.local

[DEFAULT]
bantime.increment = true
bantime.rndtime = 10
bantime.maxtime = 25920
bantime.overalljails = true
bantime = 2592
maxretry = 3
destemail = myemail
sender = myemail
mta = sendmail
action = %(action_mwl)s
action_digest = %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
                digest[name=%(__name__)s, chain="%(chain)s"]

[sshd]
enabled = true
action = %(action_digest)s 

About shebang doesn't really bother me the most important thing is that it works, so after doing some research in stackoverflow and other forum the common suggestion for this error was to hardcode env path. Good in this way for me ;)

About my issue with email I saw your code and I tried to add --to argumet:
    fail2ban_digest maildigest sshd --to myemail

In this way I got the email. Maybe there is some issue with my destemail in jail.local?

**Comment by enricotagliavini** [comment]
Possibly there is an issue with your sender. If you used the same email address as destemail when you run from command line, it might simply be that the remote MTA is refusing you email since the sender is not an authorized user. Example:

Your CentOS machine is part of mydomain.ltd and your destemail is you@example.com. You cannot send an email with sender @example.com from a machine in mydoimain.ltd. The MTA servers at mydomain.ltd can refuse you email because the sender comes from an authorized server for that domain.

I recommend to always use something@FQDN of the machine you are running on. You don't have to strictly do this, other solutions can work too when part of a domain and having a relay (and possibly more options).

**Comment by maverjk** [comment]
Hi 
As I already said, I had occasion to test your script, and to tune it in the best way. Well right now I have setup all and I have noted that the order in which script report IP in digest email is random. Is it possible to have a chronological order of IP list?

**Comment by enricotagliavini** [comment]
So you solved your problem with the email?

The order is not really random, it's ordered by amount, so that IPs with the highest number of events are listed first.

Ordering is done here https://github.com/enricotagliavini/fail2ban-digest/blob/538e38dbcbcb3995954d780f840440bb502c189f/bin/fail2ban_digest#L142

In the digest() function events are grouped by offending IP (so a single IP has multiple times associated), thus they cannot be displayed chronologically, not without significant rework.

Honestly that's also kind of redundant with just grepping your syslog / fail2ban log, that's chronological.
